# Generated by Django 3.2.23 on 2024-03-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveddata',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
