# Generated by Django 3.2.23 on 2024-03-05 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_saveddata_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saveddata',
            name='number',
        ),
    ]
