# Generated by Django 3.2.23 on 2024-03-05 20:07

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_saveddata_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveddata',
            name='image',
            field=models.ImageField(upload_to=api.models.change_image_name),
        ),
    ]
