# Generated by Django 3.2.23 on 2024-03-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_saveddata_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveddata',
            name='no_of_frames',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
