# Generated by Django 3.2.23 on 2024-03-10 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_projects_project_name'),
        ('api', '0007_alter_saveddata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveddata',
            name='project_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task.projects'),
        ),
    ]
